name: Fat source archive

on:  
  push:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules:  'true'
        fetch-depth: 0

    - name: Create clean eCAL directory
      shell: bash
      run: |
        mkdir "${{ runner.workspace }}/cleaned"
        rsync \
        --recursive \
        --delete \
        --delete-excluded \
        --exclude=".git" \
        --exclude="*.git" \
        --stats \
        $GITHUB_WORKSPACE \
        ${{ runner.workspace }}/cleaned/ecal \

    - name: Archive Action
      uses: ihiroky/archive-action@v1
      with:
        root_dir: ${{ runner.workspace }}/cleaned/ecal
        file_path: ${{ runner.workspace }}/cleaned/ecal-source-fat.tar

    - name: Upload source
      uses: actions/upload-artifact@v2
      with:
        name: ecal-source-fat
        path: ${{ runner.workspace }}/cleaned/ecal-source-fat.tar
